ruby_homepage_link: "https://www.railstutorial.org"
ruby_helppage_link: "https://www.railstutorial.org/help"
ruby_bookpage_link: "https://www.railstutorial.org/book"
ruby_contactpage_link: "https://www.railstutorial.org/contact"
ruby_newspage_link: "http://news.railstutorial.org"
sun_trainingpage_link: "http://training.sun-asterisk.vn"
